spring:
  application:
    name: daily-condition-tracker-api
  config:
    import:
      - classpath:yaml/jwt.yml
      - classpath:yaml/password.yml
      - classpath:yaml/database.yml
      - classpath:yaml/email.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json