spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_condition_tracker?charset=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: Mywndrn(!446
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect