spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

email:
  smtp:
    host: smtp.gmail.com
    port: 587
  from: junggu.ji.dev@gmail.com
  front-end-url: https://example.com
